spring:
  application:
    name: library-api-service
  datasource:
    url: jdbc:postgresql://postgres_db:5432/library_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
kafka:
  producer:
    bootstrap-address: kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094
    retries: 3
    acks: all
    linger-ms: 10
    batch-size: 16384
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    idempotence: true
